location         = "Central India"
hub_rg_name      = "hub-rg-hars-demo"
spoke1_rg_name   = "spoke1-rg-hars-demo"
spoke2_rg_name   = "spoke2-rg-hars-demo"
hub_vnet_name    = "hub-vnet-hars-demo"
spoke1_vnet_name = "spoke1-vnet-hars-demo"
spoke2_vnet_name = "spoke2-vnet-hars-demo"
fw_name          = "hub-fw-hars-demo"